version: 2

sources:
  - name: hkh_dev
    description: "Main schema with live inputs"
    schema: hkh_dev

    tables:
      - name: tbl_terms
        description: >
          Investor-level terms for equity contributions, IRR hurdles,
          and class-based distribution logic (Preferred vs Common).
        columns:
          - name: investor_serial
            description: Unique investor identifier (internal key).
          - name: full_name
            description: Full name of the investor.
          - name: anonymous_name
            description: Optional public name used in reporting.
          - name: portfolio_id
            description: Portfolio to which this investor's capital is assigned.
          - name: equity_class
            description: Either 'Preferred' or 'Common' — determines distribution order.
          - name: equity_contributed
            description: Capital committed by the investor.
          - name: base_pref_irr
            description: Preferred IRR that must be paid before promote tiers.
          - name: target_irr
            description: Maximum IRR after which this investor stops receiving distributions.

  - name: inputs
    description: "Schema containing property‐level inputs"
    schema: inputs   # ← Change to “public” or another schema name if property_inputs & capex_factors live elsewhere

    tables:
      - name: property_inputs
        description: >
          Lookup table mapping each property_id → portfolio_id, plus other
          per‐property acquisition/refinance assumptions.
        columns:
          - name: property_id
            description: Unique property identifier.
          - name: portfolio_id
            description: Portfolio to which this property belongs.
          - name: purchase_price
            description: Purchase price of the property
          - name: ds_ltv
            description: Debt service loan‐to‐value ratio
          - name: ds_int
            description: Interest rate for original loan
          - name: ds_term
            description: Term (years) of original loan
          - name: capex_per_unit
            description: CapEx assumption per unit
          - name: unit_count
            description: Total units for the property
          - name: avg_rent_per_unit
            description: Average monthly rent per unit at acquisition
          - name: opex_ratio
            description: OpEx ratio applied to EGI
          - name: vacancy_rate
            description: Vacancy rate assumption
          - name: collections_loss_rate
            description: Bad debt / collection loss rate
          - name: ds_refi_year
            description: Year refinance is modeled to occur
          - name: ds_refi_ltv
            description: LTV to apply at refinance
          - name: ds_refi_int
            description: Interest rate at refinance
          - name: ds_refi_term
            description: Term (years) of the refi loan

      - name: capex_factors
        description: >
          Year‐by‐year CapEx multipliers per property, summing to 1.00 across 20 years.
        columns:
          - name: property_id
            description: Unique ID of the property
          - name: year
            description: Portfolio year number (1–20)
          - name: capex_factor
            description: Fraction of total CapEx applied in this year (0 to 1.0)
          